apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -dev

namespace: dev

commonLabels:
  environment: dev

images:
  - name: harbor.local:31764/portifolio-devops/demo-app
    newTag: 1.0.0