apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: apps
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IubG9jYWw6MzE3NjQiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiQ2hhbmdlTWUxMjMhIiwiYXV0aCI6IllXUnRhVzQ2UTJoaGJtZGxUV1V4TWpNaCJ9fX0=